services:
  postgres:
    image: postgres:latest
    env_file:
      - db/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d

  server:
    build:
      context: .
      dockerfile: server/Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - server/.env
    volumes:
      - ./server:/app/server
      - ./common:/app/common
      - dart_tool_server:/app/server/.dart_tool
      - dart_tool_common:/app/common/.dart_tool
      - pub_cache:/root/.pub-cache
    environment:
      - ENABLE_HOT_RELOAD=true

volumes:
  postgres-data:
  dart_tool_server:
  dart_tool_common:
  pub_cache:
