name: server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  common:
    path: ../common
  crypto: ^3.0.6
  cryptography: ^2.7.0
  meta: ^1.16.0
  postgres: ^3.5.4
  shelf: ^1.4.0
  shelf_router: ^1.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  http: ^1.1.0
  lints: ^5.0.0
  test: ^1.24.0
